version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - ./volumes/postgres:/pg-data
      - ./volumes/postgres-opt:/opt
    environment:
      - PGDATA=/pg-data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - db
  odoo:
    image: elicocorp/odoo:15.0
    container_name: "${SUBDOMAIN}_odoo"
    command: start
    links:
      - postgres:db
    networks:
      - proxy
      - db
    volumes:
      - ./volumes/odoo/addons:/opt/odoo/additional_addons
      - ./volumes/odoo/filestore:/opt/odoo/data/filestore
      - ./volumes/odoo/sessions:/opt/odoo/data/sessions
      - ./volumes/odoo/ssh:/opt/odoo/ssh:ro
      - /opt/common/odoo15:/opt/odoo/sources
    environment:
      - ODOO_ADMIN_PASSWD=${ADMIN_PASSWORD}
      - ODOO_DB_USER=odoo
      - ODOO_DB_PASSWORD=${ODOO_DB_PASSWORD}
      - ODOO_PROXY_MODE=True
    labels:
      # TRAEFIK
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"
      # https: 8069
      - "traefik.http.routers.${SUBDOMAIN}.service=${SUBDOMAIN}"
      - "traefik.http.routers.${SUBDOMAIN}.rule=Host(`${SUBDOMAIN}.odoo.digitalevzw.be`)"
      - "traefik.http.routers.${SUBDOMAIN}.entrypoints=websecure"
      - "traefik.http.routers.${SUBDOMAIN}.tls.certresolver=myresolver"
      - "traefik.http.routers.${SUBDOMAIN}.middlewares=gzip,sslheader,limit"
      # https: 8072
      - "traefik.http.routers.${SUBDOMAIN}-im.service=${SUBDOMAIN}-im"
      - "traefik.http.routers.${SUBDOMAIN}-im.rule=Host(`${SUBDOMAIN}.odoo.digitalevzw.be`) && (PathPrefix(`/longpolling`))"
      - "traefik.http.routers.${SUBDOMAIN}-im.entrypoints=websecure"
      - "traefik.http.routers.${SUBDOMAIN}-im.tls.certresolver=myresolver"
      - "traefik.http.routers.${SUBDOMAIN}-im.middlewares=gzip,sslheader,limit"
      # Services
      - "traefik.http.services.${SUBDOMAIN}.loadbalancer.server.port=8069"
      - "traefik.http.services.${SUBDOMAIN}-im.loadbalancer.server.port=8072"
      # Middleware
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.limit.buffering.memRequestBodyBytes=20971520
      - traefik.http.middlewares.limit.buffering.maxRequestBodyBytes=20971520

volumes:
  db-data:


networks:
  proxy:
    external:
      name: "traefik_proxy"

  db:
    external: false
